#! /bin/sh
# @(#) $Tau: puppet/scripts/docker/entrypoint $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
##  Licensed under the Apache License, Version 2.0 (the "License");          ##
##  you may not use this file except in compliance with the License.         ##
##                                                                           ##
##  You may obtain a copy of the License at:                                 ##
##                                                                           ##
##      http://www.apache.org/licenses/LICENSE-2.0                           ##
##                                                                           ##
##  Unless required by applicable law or agreed to in writing, software      ##
##  distributed under the License is distributed on an "AS-IS" BASIS,        ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. ##
##  See the License for the specific language governing permissions and      ##
##  limitations under the License.                                           ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

NOLOGIN='/var/lib/initscripts/nologin'

if test -x /sbin/init ; then
	touch ${NOLOGIN}
	/sbin/init --init &
	sleep 1
	while test -f ${NOLOGIN} ; do
		sleep 1
	done
fi

cd "$HOME"
exec "$@"
