#! /bin/sh
# @(#) $Tau: puppet/scripts/docker/ready $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
##  Licensed under the Apache License, Version 2.0 (the "License");          ##
##  you may not use this file except in compliance with the License.         ##
##                                                                           ##
##  You may obtain a copy of the License at:                                 ##
##                                                                           ##
##      http://www.apache.org/licenses/LICENSE-2.0                           ##
##                                                                           ##
##  Unless required by applicable law or agreed to in writing, software      ##
##  distributed under the License is distributed on an "AS-IS" BASIS,        ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. ##
##  See the License for the specific language governing permissions and      ##
##  limitations under the License.                                           ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

. /etc/default/rcS

NOLOGIN='/var/lib/initscripts/nologin'

if test -r ${NOLOGIN} ; then
	[ x"${QUIET}" = xyes ] || printf "\033[0;1mContainer %s is ready.\033[0m\n" $(hostname | cut -f1 -d.) >/dev/console
	rm -f ${NOLOGIN}
fi
while true ; do
	sleep 3600
done
