#! /bin/sh
# $Tau: puppet/docker/ready $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
## This file forms part of the Tau Project and is subject to copyright.      ##
##                                                                           ##
## For full licensing terms, including conditions for redistribution, please ##
## consult the README document accompanying the source distribution:         ##
##                                                                           ##
##   <https://github.com/tauproject/puppet>                                  ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

. /etc/default/rcS

NOLOGIN='/var/lib/initscripts/nologin'

if test -r ${NOLOGIN} ; then
	[ x"${QUIET}" = xyes ] || printf "\033[0;1mContainer %s is ready.\033[0m\n" $(hostname | cut -f1 -d.) >/dev/console
	rm -f ${NOLOGIN}
fi
while true ; do
	sleep 3600
done
