#! /bin/sh
# $Tau: puppet/docker/startup $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
## This file forms part of the Tau Project and is subject to copyright.      ##
##                                                                           ##
## For full licensing terms, including conditions for redistribution, please ##
## consult the README document accompanying the source distribution:         ##
##                                                                           ##
##   <https://github.com/tauproject/puppet>                                  ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

NOLOGIN='/var/lib/initscripts/nologin'

if test -x /sbin/init ; then
	touch ${NOLOGIN}
	/sbin/init --init &
	sleep 1
	while test -f ${NOLOGIN} ; do
		sleep 1
	done
fi

cd "$HOME"
exec "$@"
